name: Starting project

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  #   paths:
  #     - 'aws-cloud/ec2/*'
  # pull_request:
  #   branches:
  #     - 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger docker Workflow to build image
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/bh-gaur/docker/dispatches \
            -d '{"event_type": "trigger-workflow-1"}'

      - name: Sleep until triggered job complete
        run: |
            sleep 60

      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest stable version of actions/checkout
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.0.0'  # Specify your desired Terraform version here

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Change to your desired AWS region

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACCESS_KEY_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Checkout Terraform repository
        run: |
          git clone git@github.com:bh-gaur/aws.git
          
      - name: Terraform Init
        run: |
          cd aws/project/docker-test
          terraform init
          terraform validate  # Ensures Terraform configuration is valid

      - name: Terraform Plan
        run: |
          cd aws/project/docker-test
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd aws/project/docker-test
          terraform apply -auto-approve tfplan
